connect to API
Somdotta07/bookstore-react-redux pull request #3
Opened 2021-12-07 13:34 UTC by Somdotta07

- Connected with  Bookstore API
- Refactored the codes
- Used middleware

2021-12-07 15:02 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @Somdotta07,

Good job so far!
✔️ Good documentation
✔️ Nicely modularized code
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-07 15:02 UTC, TedLivist commented on src/components/BooksPage.js
>      </div>
Please take a look at the image below
- [ ] I have deleted one book but it is still on the redux store and on the page. As specified in the project guidelines, you should make async requests that persist on the server. You seem to have done this correctly. However, your changes are not stored correctly on the redux store when I add or delete a book. I need to reload the browser for the store to be updated from the server.
  
  Remember, this project is merely a refactor of the previous one and so just like your previous `create-remove` project, the books list should be updated without page reload. Kindly fix this behavior.

  ![somdo-books](https://user-images.githubusercontent.com/36542986/145052653-45940f57-6de6-4581-b662-79ff745dc626.jpg)

2021-12-08 10:05 UTC, Somdotta07 commented
Fixed the problem observed by the previous reviewer.

2021-12-08 10:20 UTC, dasileker approved these changes
## **Hi @Somdotta07 ,** 

## **Congratulations! 🎉 Project Approved ✅**
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 
 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-08 10:21 UTC, merged